# Generated by Django 5.0.1 on 2024-01-31 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='auth_code',
            field=models.CharField(default='000000', max_length=6),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('us', 'user'), ('mo', 'moderator'), ('ad', 'admin')], default='us', max_length=2),
        ),
    ]
