# Generated by Django 5.0.1 on 2024-01-31 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distribution',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='mailinglist',
            options={'verbose_name': 'База для рассылок', 'verbose_name_plural': 'Базы для рассылок'},
        ),
        migrations.AlterModelOptions(
            name='message',
            options={'verbose_name': 'Сообщение', 'verbose_name_plural': 'Сообщения'},
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'verbose_name': 'Подписчик', 'verbose_name_plural': 'Подписчики'},
        ),
        migrations.AddField(
            model_name='distribution',
            name='status',
            field=models.CharField(choices=[('new', 'new one'), ('on', 'Its up and running'), ('off', 'Stopped')], default='new', max_length=3),
        ),
    ]
