# Generated by Django 5.0.1 on 2024-02-04 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mailers', '0005_distributionlog_distribution_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='distribution',
            options={'permissions': [('change_status', 'Can change status (and STOP it) for distribution')], 'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылки'},
        ),
        migrations.AlterModelOptions(
            name='distributionlog',
            options={'ordering': ('-task_start_date', 'distribution'), 'verbose_name': 'Логи рассылки', 'verbose_name_plural': 'Логи рассылок'},
        ),
        migrations.AlterModelOptions(
            name='subscriber',
            options={'ordering': ('-datetime_added', 'email'), 'verbose_name': 'Подписчик', 'verbose_name_plural': 'Подписчики'},
        ),
    ]
